version: "3.7"
services:
  caddy:
    container_name: caddy-comboom.sucht
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=http://localhost:80
      - SEARXNG_TLS=internal
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: always
  redis:
    container_name: redis-comboom.sucht
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - searxng
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always
  searxng:
    container_name: searxng-comboom.sucht
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "3066:8080"
    volumes:
      - searxng-data:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:3066/
      - INSTANCE_NAME=comboom.sucht
    restart: always
networks:
  searxng:
    ipam:
      driver: default
volumes:
  caddy-data:
  caddy-config:
  redis-data:
  searxng-data: