services:
  caddy:
    container_name: caddy-comboom.sucht
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=search.localhost
      - SEARXNG_TLS=internal
      - IT_TOOLS_HOSTNAME=it-tools.localhost
      - IT_TOOLS_TLS=internal
      - STIRLING_PDF_HOSTNAME=stirling-pdf.localhost
      - STIRLING_PDF_TLS=internal
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: always
  redis:
    container_name: redis-comboom.sucht
    image: docker.io/library/redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - local-services
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always
  searxng:
    container_name: searxng-comboom.sucht
    image: searxng/searxng:latest
    networks:
      - local-services
    ports:
      - "8080:8080"
    volumes:
      - searxng-data:/etc/searxng:rw
      - ./searxng/settings.yml:/etc/searxng/settings.yml:rw
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:rw
    environment:
      - SEARXNG_BASE_URL=https://search.localhost
      - INSTANCE_NAME=comboom.sucht
    restart: always
  it-tools:
    container_name: it-tools-comboom.sucht
    image: corentinth/it-tools:latest
    ports:
      - "8081:80"
    networks:
      - local-services
    restart: always
  stirling-pdf:
    container_name: stirling-pdf-comboom.sucht
    image: stirlingtools/stirling-pdf:latest-fat
    ports:
      - '8082:8080'
    volumes:
      - ./pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./pdf/extraConfigs:/configs
      - ./pdf/customFiles:/customFiles/
      - ./pdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
    networks:
      - local-services
    restart: always

networks:
  local-services:
    ipam:
      driver: default
volumes:
  caddy-data:
  caddy-config:
  redis-data:
  searxng-data:
