services:
  caddy:
    container_name: caddy-comboom.sucht
    image: caddy:2-alpine
    pull_policy: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=search.localhost
      - IT_TOOLS_HOSTNAME=it-tools.localhost
      - STIRLING_PDF_HOSTNAME=stirling-pdf.localhost
      - DEV_HOSTNAME=dev.localhost
      - APACHE2_HOSTNAME=apache2.localhost
      - PORTAINER_HOSTNAME=portainer.localhost
      - HOMER_HOSTNAME=localhost
      - TLS=internal
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    restart: always
  redis:
    container_name: redis-comboom.sucht
    image: docker.io/library/redis:alpine
    pull_policy: always
    command: redis-server --save 30 1 --loglevel warning
    networks:
      - local-services
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always
  searxng:
    container_name: searxng-comboom.sucht
    image: searxng/searxng:latest
    pull_policy: always
    networks:
      - local-services
    ports:
      - "8082:8080"
    volumes:
      - searxng-data:/etc/searxng:rw
      - ./searxng/settings.yml:/etc/searxng/settings.yml:rw
      - ./searxng/limiter.toml:/etc/searxng/limiter.toml:rw
    environment:
      - SEARXNG_BASE_URL=https://search.localhost
      - INSTANCE_NAME=comboom.sucht
    restart: always
  it-tools:
    container_name: it-tools-comboom.sucht
    image: ghcr.io/sharevb/it-tools:nightly
    pull_policy: always
    ports:
      - "8081:8080"
    environment:
      NODE_ENV: production
    networks:
      - local-services
    restart: always
  stirling-pdf:
    container_name: stirling-pdf-comboom.sucht
    image: stirlingtools/stirling-pdf:latest-fat
    pull_policy: always
    ports:
      - '8080:8080'
    volumes:
      - ./pdf/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./pdf/extraConfigs:/configs
      - ./pdf/customFiles:/customFiles/
      - ./pdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SERVER_HOSTNAME=stirling-pdf.localhost
    deploy:
      resources:
        limits:
          cpus: '4.0'
    networks:
      - local-services
    restart: always
  portainer:
    container_name: portainer-comboom.sucht
    image: portainer/portainer-ce:latest
    pull_policy: always
    ports:
            - '8083:9000'
            - '8084:9443'
            - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: always
    networks:
      - local-services
  homer:
    image: b4bz/homer
    container_name: homer-comboom.sucht
    volumes:
      - ./homer/assets:/www/assets # Make sure your local config directory exists
    ports:
      - 8085:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: always
    networks:
      - local-services
    pull_policy: always

networks:
  local-services:
    ipam:
      driver: default
volumes:
  caddy-data:
  caddy-config:
  redis-data:
  searxng-data:
  portainer-data:
