- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  slug: home
  title: Home
  center-vertically: true
  expand-mobile-page-navigation: true
  show-mobile-header: true
  columns:
    - size: small
      title: Social
      widgets:
        - type: twitch-channels
          channels:
            - tsoding
            - christitustech
        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCEbYhDd6c6vngsF5PQpFVWg # Tsoding
            - UCrqM0Ym_NbK1fqeQG2VIohg # Tsoding Daily
            - UCqwGaUvq_l0RKszeHhZ5leA # PietSmiet
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
          style: vertical-list
    - size: full
      widgets:
        - type: search
          search-engine: http://search.localhost/search?q={QUERY}
          new-tab: true
          autofocus: true
          placeholder: Search the web...
        - type: group
          title: Repositories
          widgets:
            - type: releases
              cache: 1d
              # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              # read-only token from your Github account settings and use it here to increase the limit.
              token: ${GITHUB_TOKEN}
              show-source-icon: true
              repositories:
                - searxng/searxng
                - NginxProxyManager/nginx-proxy-manager
                - phpmyadmin/docker
                - sharevb/it-tools
                - Stirling-Tools/Stirling-PDF
                - glanceapp/glance
                - MariaDB/mariadb-docker
            - type: repository
              title: SearXNG
              token: ${GITHUB_TOKEN}
              repository: searxng/searxng
            - type: repository
              title: Nginx Proxy Manager
              token: ${GITHUB_TOKEN}
              repository: NginxProxyManager/nginx-proxy-manager
            - type: repository
              title: phpMyAdmin
              token: ${GITHUB_TOKEN}
              repository: phpmyadmin/docker
            - type: repository
              title: IT Tools
              token: ${GITHUB_TOKEN}
              repository: sharevb/it-tools
            - type: repository
              title: Stirling-PDF
              token: ${GITHUB_TOKEN}
              repository: Stirling-Tools/Stirling-PDF
            - type: repository
              title: Glance | Dashboard
              token: ${GITHUB_TOKEN}
              repository: glanceapp/glance
            - type: repository
              title: MariaDB
              token: ${GITHUB_TOKEN}
              repository: MariaDB/mariadb-docker

    - size: small
      title: Infos
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: Europe/Paris
              label: Paris
            - timezone: America/New_York
              label: New York
            - timezone: Asia/Tokyo
              label: Tokyo
        - type: calendar
          first-day-of-week: monday
        - type: weather
          location: Berlin, Germany
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: group
          title: Services
          widgets:
            - type: monitor
              cache: 1m
              title: Services
              sites:
                - title: SearXNG
                  url: http://search.localhost/
                - title: Zoraxy
                  url: http://zoraxy.localhost/
                - title: IT Tools
                  url: http://it-tools.localhost/
                - title: Stirling PDF
                  url: http://stirling-pdf.localhost/
                - title: HadgeDoc
                  url: http://hedgedoc.localhost/
                - title: paperless-ngx
                  url: http://paperless.localhost/
                - title: phpMyAdmin
                  url: http://phpmyadmin.localhost/
                - title: Portainer
                  url: http://portainer.localhost/
            - type: docker-containers
              title: Docker Containers
              hide-by-default: true
