- name: Social
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  slug: social
  title: Social
  center-vertically: true
  expand-mobile-page-navigation: true
  show-mobile-header: true
  columns:
    - size: full
      widgets:
        - type: search
          search-engine: http://search.localhost/search?q={QUERY}
          new-tab: true
          autofocus: true
          placeholder: Search the web...
        - type: twitch-channels
          channels:
            - tsoding
            - christitustech
        - type: videos
          channels:
            - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
            - UCEbYhDd6c6vngsF5PQpFVWg # Tsoding
            - UCrqM0Ym_NbK1fqeQG2VIohg # Tsoding Daily
            - UCqwGaUvq_l0RKszeHhZ5leA # PietSmiet
            - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium
          style: grid-cards