# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

general:
  instance_name: "comboom.sucht"

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "f5d817c17939446ea1bbd875d6b65b6aebff9cd1640fcc646d04def498495240afa0e75662570d758320af00e7e4250847567b3448181cf5bb5be4459680e7783b1f31f40a6cdfc96c72eef75d03628a0f661d449c7ecae84fbd6e589851ee57787d96f016f3c527abf0d8e181d7c7a37884d5f487494506df3e2d1c308efb67"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  public_instance: false
ui:
  static_use_hash: true
  default_locale: "de"
  query_in_title: true
  infinite_scroll: true
  center_alignment: false
  cache_url: https://web.archive.org/web/
  default_theme: simple
  theme_args:
    simple_style: dark
  results_on_new_tab: true
  search_on_category_select: true
  hotkeys: default
redis:
  url: redis://redis:6379/0
search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: "de"
  languages:
  - all
  - en
  - en-US
  - de
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  suspended_times:
    SearxEngineAccessDenied: 86400
    SearxEngineCaptcha: 86400
    SearxEngineTooManyRequests: 3600
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    recaptcha_SearxEngineCaptcha: 604800
  formats:
    - html
    
enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Ahmia blacklist'
  - 'Open Access DOI rewrite'